d3d7.emulateFSAA=false
d3d8.forceLegacyDiscard=false
d3d9.deferSurfaceCreation=true
d3d9.deviceLossOnFocusLoss=false
d3d9.floatEmulation=false
d3d11.forceComputeLdsBarriers=false
d3d11.forceComputeUavBarriers=false
d3d11.relaxedBarriers=true
d3d11.relaxedGraphicsBarriers=true
dxgi.deferSurfaceCreation=true
dxvk.disableNvLowLatency2=true
dxvk.enableAsync=true
dxvk.enableDebugUtils=false
dxvk.enableDescriptorBuffer=true
dxvk.enableGraphicsPipelineLibrary=auto
dxvk.enableMemoryDefrag=true
dxvk.gplAsyncCache=true
dxvk.hud=api
dxvk.latencySleep=false
dxvk.tearFree=false
dxvk.trackPipelineLifetime=true
