
[font]
size = 16.0

[font.bold]
family = "PxPlus ToshibaTxL1 8x16"
style = "Bold"

[font.italic]
family = "PxPlus ToshibaTxL1 8x16"
style = "Italic"

[font.normal]
family = "PxPlus ToshibaTxL1 8x16"
style = "Regular"

[font.offset]
x = 0
y = 0

[general]
import = ["~/.config/alacritty/tokyo-night-storm.toml"]
